# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 14:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, unique=True, verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['category'],
                'verbose_name_plural': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('is_canceled', models.BooleanField(default=False, verbose_name='cancelado')),
            ],
            options={
                'verbose_name': 'contrato',
                'ordering': ['proposal'],
                'verbose_name_plural': 'contratos',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('address', models.CharField(max_length=80, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, max_length=80, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=80, null=True, verbose_name='bairro')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Brasília'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('first_name', models.CharField(max_length=50, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1, verbose_name='gênero')),
                ('treatment', models.CharField(blank=True, choices=[('a', 'Arq.'), ('aa', 'Arqa.'), ('d', 'Dona'), ('dr', 'Dr.'), ('dra', 'Dra.'), ('e', 'Eng.'), ('ea', 'Engª.'), ('p', 'Prof.'), ('pa', 'Profa.'), ('sr', 'Sr.'), ('sra', 'Sra.'), ('srta', 'Srta.')], max_length=4, null=True, verbose_name='tratamento')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='empresa')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='departamento')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 3')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('blocked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('cnpj', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CNPJ')),
                ('ie', models.CharField(blank=True, max_length=12, null=True, verbose_name='inscrição estadual')),
                ('type_customer', models.CharField(choices=[('c', 'construtora'), ('a', 'arquitetura'), ('p', 'particular')], max_length=1, verbose_name='tipo de cliente')),
            ],
            options={
                'verbose_name': 'cliente',
                'ordering': ['first_name'],
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('address', models.CharField(max_length=80, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, max_length=80, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=80, null=True, verbose_name='bairro')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Brasília'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1, verbose_name='gênero')),
                ('treatment', models.CharField(blank=True, choices=[('a', 'Arq.'), ('aa', 'Arqa.'), ('d', 'Dona'), ('dr', 'Dr.'), ('dra', 'Dra.'), ('e', 'Eng.'), ('ea', 'Engª.'), ('p', 'Prof.'), ('pa', 'Profa.'), ('sr', 'Sr.'), ('sra', 'Sra.'), ('srta', 'Srta.')], max_length=4, null=True, verbose_name='tratamento')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='empresa')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='departamento')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 3')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('blocked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('date_entry', models.DateTimeField(blank=True, null=True, verbose_name='data de entrada')),
                ('date_release', models.DateTimeField(blank=True, null=True, verbose_name='data de saída')),
            ],
            options={
                'verbose_name': 'funcionário',
                'ordering': ['user__first_name'],
                'verbose_name_plural': 'funcionários',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('priority', models.CharField(choices=[('u', 'Urgente'), ('a', 'Alta'), ('n', 'Normal'), ('b', 'Baixa')], default='n', max_length=10, verbose_name='prioridade')),
                ('description', models.TextField(blank=True, max_length=100, null=True, verbose_name='descrição')),
                ('is_entry', models.BooleanField(default=False, verbose_name='dado entrada')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_category', to='core.Category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'entrada',
                'ordering': ['-priority', 'created'],
                'verbose_name_plural': 'entradas',
            },
        ),
        migrations.CreateModel(
            name='NumLastProposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_last_prop', models.PositiveIntegerField(verbose_name='número')),
            ],
            options={
                'verbose_name': 'número último orçamento',
                'verbose_name_plural': 'número último orçamento',
            },
        ),
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occupation', models.CharField(max_length=50, unique=True, verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'cargo',
                'ordering': ['occupation'],
                'verbose_name_plural': 'cargos',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('address', models.CharField(max_length=80, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, max_length=80, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=80, null=True, verbose_name='bairro')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Brasília'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('first_name', models.CharField(max_length=50, verbose_name='nome')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='sobrenome')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('gender', models.CharField(choices=[('M', 'masculino'), ('F', 'feminino')], max_length=1, verbose_name='gênero')),
                ('treatment', models.CharField(blank=True, choices=[('a', 'Arq.'), ('aa', 'Arqa.'), ('d', 'Dona'), ('dr', 'Dr.'), ('dra', 'Dra.'), ('e', 'Eng.'), ('ea', 'Engª.'), ('p', 'Prof.'), ('pa', 'Profa.'), ('sr', 'Sr.'), ('sra', 'Sra.'), ('srta', 'Srta.')], max_length=4, null=True, verbose_name='tratamento')),
                ('company', models.CharField(blank=True, max_length=50, null=True, verbose_name='empresa')),
                ('department', models.CharField(blank=True, max_length=50, null=True, verbose_name='departamento')),
                ('phone1', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 2')),
                ('phone3', models.CharField(blank=True, max_length=20, null=True, verbose_name='fone 3')),
                ('cpf', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(blank=True, max_length=11, null=True, verbose_name='RG')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('blocked', models.BooleanField(default=False, verbose_name='bloqueado')),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_occupation', to='core.Occupation', verbose_name='cargo')),
            ],
            options={
                'verbose_name': 'contato',
                'ordering': ['first_name'],
                'verbose_name_plural': 'contatos',
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modificado em')),
                ('num_prop', models.PositiveIntegerField(verbose_name='número')),
                ('type_prop', models.CharField(blank=True, choices=[('R', 'R'), ('OP', 'OP')], max_length=20, null=True, verbose_name='tipo de orçamento')),
                ('num_type_prop', models.PositiveIntegerField(default=0, verbose_name='número da revisão')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='descrição')),
                ('status', models.CharField(choices=[('c', 'cancelado'), ('elab', 'em elaboração'), ('p', 'pendente'), ('co', 'concluido'), ('a', 'aprovado')], default='elab', max_length=4)),
                ('date_conclusion', models.DateTimeField(blank=True, null=True, verbose_name='data de conclusão')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='valor')),
                ('obs', models.TextField(blank=True, max_length=100, null=True, verbose_name='observação')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_category', to='core.Category', verbose_name='categoria')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_employee', to='core.Employee', verbose_name='orçamentista')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_person', to='core.Person', verbose_name='contato')),
            ],
            options={
                'verbose_name': 'orçamento',
                'ordering': ['id'],
                'verbose_name_plural': 'orçamentos',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal', models.BooleanField(default=True, verbose_name='interno')),
                ('commissioned', models.BooleanField(default=True, verbose_name='comissionado')),
                ('commission', models.DecimalField(blank=True, decimal_places=2, default=0.01, max_digits=6, verbose_name='comissão')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_employee', to='core.Employee', verbose_name='funcionário')),
            ],
            options={
                'verbose_name': 'vendedor',
                'ordering': ['employee__user__first_name'],
                'verbose_name_plural': 'vendedores',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80, verbose_name='endereço')),
                ('complement', models.CharField(blank=True, max_length=80, null=True, verbose_name='complemento')),
                ('district', models.CharField(blank=True, max_length=80, null=True, verbose_name='bairro')),
                ('city', models.CharField(max_length=80, verbose_name='cidade')),
                ('uf', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AM', 'Amazonas'), ('AP', 'Amapá'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Brasília'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, verbose_name='CEP')),
                ('name_work', models.CharField(max_length=100, unique=True, verbose_name='obra')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_customer', to='core.Customer', verbose_name='cliente')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_person', to='core.Person', verbose_name='contato')),
            ],
            options={
                'verbose_name': 'obra',
                'ordering': ['name_work'],
                'verbose_name_plural': 'obras',
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_seller', to='core.Seller', verbose_name='vendedor'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_work', to='core.Work', verbose_name='obra'),
        ),
        migrations.AddField(
            model_name='entry',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_person', to='core.Person', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='entry',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_seller', to='core.Seller', verbose_name='vendedor'),
        ),
        migrations.AddField(
            model_name='entry',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entry_work', to='core.Work', verbose_name='obra'),
        ),
        migrations.AddField(
            model_name='employee',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_occupation', to='core.Occupation', verbose_name='cargo'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contract',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_customer', to='core.Customer', verbose_name='contratante'),
        ),
        migrations.AddField(
            model_name='contract',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract_proposal', to='core.Proposal', verbose_name='orçamento'),
        ),
    ]
