# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-17 02:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['username'], 'verbose_name': 'funcionário', 'verbose_name_plural': 'funcionários'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_entry',
        ),
    ]
