# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160314_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person_type',
            field=models.CharField(choices=[('c', 'cliente'), ('p', 'contato')], max_length=1, verbose_name='cliente ou contato'),
        ),
    ]
