# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-01 01:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160229_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneperson',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Employee'),
        ),
    ]
