# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-26 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20161126_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='ie',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
        migrations.AlterField(
            model_name='person',
            name='ie',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='inscrição estadual'),
        ),
        migrations.AlterField(
            model_name='person',
            name='rg',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='RG'),
        ),
    ]
