# Generated by Django 2.1.3 on 2018-12-03 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_auto_20181203_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('I', 'não informado'), ('M', 'masculino'), ('F', 'feminino')], default='I', max_length=1, null=True, verbose_name='gênero'),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(blank=True, choices=[('I', 'não informado'), ('M', 'masculino'), ('F', 'feminino')], default='I', max_length=1, null=True, verbose_name='gênero'),
        ),
    ]
