# Generated by Django 2.1.3 on 2018-12-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_auto_20181214_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cnpj',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='person',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='CPF'),
        ),
    ]
